#!/bin/zsh

Z_ROOT=$PWD

source main.zsh

z.io.clear
z.io "File watching..."

local fswatch_opts=(-r lib test mod)

# fsevents_monitor is not supported in WSL, so poll_monitor will be used instead.
# Using the default monitor (inotify) will detect file access events. 
# However, all event names will be PlatformSpecific, making it impossible to sort events.
if z.str.includes $(uname -r) "WSL"; then
  fswatch_opts+=(-m poll_monitor)
else
  fswatch_opts+=(-m fsevents_monitor)
fi

local moved=false

fswatch ${fswatch_opts[@]} | while read file; do
  z.io.clear
  local relative_path=${file#$PWD/}
  z.io "File changed: $relative_path"
  z.is.false $moved && cd test && moved=true
  z.t -f
done
