import {
  createConnection,
  TextDocuments,
  TextDocumentSyncKind,
  ProposedFeatures,
  DefinitionParams,
  DiagnosticSeverity,
  DocumentDiagnosticReportKind,
  DidChangeWatchedFilesNotification,
  CompletionItem,
  CompletionParams,
  CompletionItemKind,
  HoverParams,
  Location,
  MarkupKind,
  InitializeParams,
  InitializeResult,
} from 'vscode-languageserver/node';
import { TextDocument } from 'vscode-languageserver-textdocument';

export {
  createConnection,
  TextDocuments,
  TextDocumentSyncKind,
  ProposedFeatures,
  DefinitionParams,
  DiagnosticSeverity,
  DocumentDiagnosticReportKind,
  DidChangeWatchedFilesNotification,
  CompletionItem,
  CompletionParams,
  CompletionItemKind,
  HoverParams,
  Location,
  MarkupKind,
  InitializeParams,
  InitializeResult,
  TextDocument,
};
