name: CI

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:
    branches:
      - main
      - "feat/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up zsh
        run: sudo apt-get install -y zsh
      - name: Run tests
        run: |
          source main.zsh
          z.t
